# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cE7fcrofv7q4QZkk7ER5ugQP6KZUPHaL
"""

import math
import matplotlib.pyplot as plt
import numpy as np
d = 7.2
n1 = 1.447
n2 = 1.442
NA = math.sqrt(n1**2 - n2**2)
lambda_cutoff = math.pi*d*NA/2.405
L = np.arange(0.8,1.6,0.01)
v = []
for i in L:
 v.append(math.pi*d*NA/i)
plt.plot(L,v)
plt.title("Single Mode Operation Plot")
plt.xlabel("Wavelength")
plt.ylabel("V-number")
plt.axhspan(min(v),2.405,facecolor='b',alpha = 0.2)
plt.axvspan(lambda_cutoff,1.6,facecolor='r',alpha = 0.2)
plt.text(1.3,2.1,'Single mode operation')
plt.show()